package it.kapfer.bankteller.crypto

import it.kapfer.bankteller.database.BankTellerDatabase
import org.bouncycastle.asn1.x500.X500Name
import org.bouncycastle.cert.jcajce.JcaX509CertificateConverter
import org.bouncycastle.cert.jcajce.JcaX509v3CertificateBuilder
import org.bouncycastle.operator.jcajce.JcaContentSignerBuilder
import java.math.BigInteger
import java.security.KeyPair
import java.security.cert.X509Certificate
import java.util.Base64
import java.util.Date

/**
 * Holds PEM-encoded key material generated by [KeyPairGenerator].
 */
data class GeneratedKeyMaterial(
    val privateKeyPem: String,
    val certificatePem: String,
)

/**
 * Generates a 4096-bit RSA key pair and a self-signed X.509 v3 certificate.
 *
 * The private key is encoded as PKCS#8 PEM and the certificate as PEM.
 * Canonical PEM utilities live in [it.kapfer.bankteller.enablebanking.PemUtils];
 * local helpers are used here to avoid cross-lane compile ordering issues.
 */
class KeyPairGenerator {

    /**
     * Generates the key pair and certificate material.
     */
    fun generate(): GeneratedKeyMaterial {
        val keyPair = generateKeyPair()
        val certificate = buildCertificate(keyPair)
        return GeneratedKeyMaterial(
            privateKeyPem = encodePrivateKeyPem(keyPair.private),
            certificatePem = encodeCertificatePem(certificate),
        )
    }

    // ---- internal helpers ----

    private fun generateKeyPair(): KeyPair {
        val generator = java.security.KeyPairGenerator.getInstance("RSA")
        generator.initialize(4096)
        return generator.generateKeyPair()
    }

    private fun buildCertificate(keyPair: KeyPair): X509Certificate {
        val issuer = X500Name("CN=BankTeller")
        val serial = BigInteger.valueOf(System.currentTimeMillis())
        val notBefore = Date()
        val notAfter = Date(System.currentTimeMillis() + 365L * 24 * 60 * 60 * 1000)

        val certBuilder = JcaX509v3CertificateBuilder(
            issuer,
            serial,
            notBefore,
            notAfter,
            issuer, // self-signed — subject equals issuer
            keyPair.public,
        )

        val signer = JcaContentSignerBuilder("SHA256withRSA").build(keyPair.private)
        return JcaX509CertificateConverter().getCertificate(certBuilder.build(signer))
    }

    // ---- PEM encoding (local helpers; canonical version: PemUtils in enablebanking) ----

    private fun encodePrivateKeyPem(key: java.security.PrivateKey): String {
        val base64 = Base64.getMimeEncoder(64, "\n".toByteArray()).encodeToString(key.encoded)
        return "-----BEGIN PRIVATE KEY-----\n$base64\n-----END PRIVATE KEY-----\n"
    }

    private fun encodeCertificatePem(cert: X509Certificate): String {
        val base64 = Base64.getMimeEncoder(64, "\n".toByteArray()).encodeToString(cert.encoded)
        return "-----BEGIN CERTIFICATE-----\n$base64\n-----END CERTIFICATE-----\n"
    }
}

/**
 * Generates a fresh key pair and self-signed certificate via [KeyPairGenerator],
 * persists **only the private key** to `system_config` under
 * `enable_banking_private_key`, and returns **only the certificate PEM**
 * (public material).
 *
 * By signature this function guarantees the private key is never exposed to
 * the caller — it is written straight to the database and discarded from scope.
 *
 * @param database  the application database whose `systemConfigQueries` are use.
 * @return the PEM-encoded X.509 certificate (safe for transmission to EB).
 */
fun generateAndPersist(database: BankTellerDatabase): String {
    val material = KeyPairGenerator().generate()
    database.systemConfigQueries.insertOrReplace(
        "enable_banking_private_key",
        material.privateKeyPem,
    )
    return material.certificatePem
}
