package it.kapfer.bankteller.onboarding

import io.ktor.client.request.*
import io.ktor.client.statement.*
import io.ktor.http.*
import io.ktor.server.sessions.*
import io.ktor.server.testing.*
import it.kapfer.bankteller.database.BankTellerDatabase
import it.kapfer.bankteller.enablebanking.AccountResource
import it.kapfer.bankteller.module
import it.kapfer.bankteller.server.DatabaseFactory
import it.kapfer.bankteller.server.KeyStore
import it.kapfer.bankteller.server.LegacySessionPayload
import kotlinx.serialization.json.Json
import kotlin.test.AfterTest
import kotlin.test.BeforeTest
import kotlin.test.Test
import kotlin.test.assertEquals
import kotlin.test.assertFalse
import kotlin.test.assertTrue

/**
 * Verifies the one-time legacy-cookie import at POST /api/login (task 10.4).
 *
 * When a user presents an old-format `bankteller-session` cookie (carrying
 * `ebSessionId` + `accountsJson`) and the `eb_sessions` table is still empty,
 * the login handler imports one eb_sessions row + its accounts rows before
 * issuing the fresh slim cookie. A second login (table now non-empty) imports
 * nothing — the import is idempotent / one-shot.
 *
 * Uses a per-test temp-file database (NOT `:memory:`) so the test's own
 * `DatabaseFactory.init()` and the module's internal `DatabaseFactory.init()`
 * share the same SQLite file — mirroring the pattern in `AccountLinkingRoutesTest`.
 */
class LegacyCookieImportTest {

    private lateinit var database: BankTellerDatabase
    private var dbFile: java.io.File? = null

    @BeforeTest
    fun setUp() {
        val file = java.io.File.createTempFile("bt-legacy-import", ".db")
        file.deleteOnExit()
        dbFile = file
        System.setProperty("database.path", file.absolutePath)
        database = DatabaseFactory.init()
    }

    @AfterTest
    fun tearDown() {
        System.clearProperty("database.path")
        dbFile?.delete()
    }

    /**
     * Build a signed `bankteller-session` cookie value encoding a
     * [LegacySessionPayload], exactly as the old server would have issued it.
     */
    private fun buildLegacyCookie(
        payload: LegacySessionPayload,
        signingKeyHex: String,
    ): String {
        val signingKey = signingKeyHex.chunked(2).map { it.toInt(16).toByte() }.toByteArray()
        val json = Json { ignoreUnknownKeys = true }
        val payloadJson = json.encodeToString(LegacySessionPayload.serializer(), payload)
        val transformer = SessionTransportTransformerMessageAuthentication(signingKey)
        return transformer.transformWrite(payloadJson)
    }

    @Test
    fun login_withLegacyCookie_importsSessionAndAccounts() = testApplication {
        application { module() }

        // The signing key is generated by KeyStore.init() during module() and
        // stored in system_config. Read it back so we can sign the legacy cookie.
        val signingKeyHex = KeyStore.init(database)

        val accountsJson = Json.encodeToString(
            kotlinx.serialization.builtins.ListSerializer(AccountResource.serializer()),
            listOf(
                AccountResource(uid = "acc-1", iban = "AT611904300234573201", currency = "EUR", name = "Main account"),
                AccountResource(uid = "acc-2", iban = null, currency = "EUR", name = "Savings"),
            ),
        )
        val legacyPayload = LegacySessionPayload(
            username = "admin",
            psuIdHash = "hash123",
            aspspName = "TestBank",
            aspspCountry = "AT",
            psuType = "personal",
            ebSessionId = "eb-session-legacy-001",
            accountsJson = accountsJson,
            authError = null,
        )
        val signedCookie = buildLegacyCookie(legacyPayload, signingKeyHex)

        // Pre-condition: no sessions in the DB.
        assertFalse(database.ebSessionsQueries.hasAnySession().executeAsOne())

        val response = client.post("/api/login") {
            header(HttpHeaders.ContentType, ContentType.Application.Json.toString())
            header(HttpHeaders.Cookie, "bankteller-session=$signedCookie")
            setBody("""{"username":"admin","password":"changeme"}""")
        }

        assertEquals(HttpStatusCode.OK, response.status)

        // Post-condition: one eb_sessions row + two accounts rows imported.
        val sessions = database.ebSessionsQueries.selectAllSessions().executeAsList()
        assertEquals(1, sessions.size)
        assertEquals("eb-session-legacy-001", sessions[0].session_id)
        assertEquals("TestBank", sessions[0].aspsp_name)
        assertEquals("AT", sessions[0].aspsp_country)
        assertEquals("personal", sessions[0].psu_type)

        val accounts = database.ebSessionsQueries
            .selectAccountsBySessionIds(listOf(sessions[0].id))
            .executeAsList()
        assertEquals(2, accounts.size)
        assertTrue(accounts.any { it.iban == "AT611904300234573201" && it.name == "Main account" })
        assertTrue(accounts.any { it.iban == null && it.name == "Savings" })
    }

    @Test
    fun login_withLegacyCookie_whenSessionsAlreadyExist_importsNothing() = testApplication {
        application { module() }

        val signingKeyHex = KeyStore.init(database)

        // Pre-populate the DB with an existing session so hasAnySession() returns true.
        EbSessionStore(database).mergeSession(
            sessionId = "eb-session-existing",
            aspspName = "ExistingBank",
            aspspCountry = "DE",
            psuType = "personal",
            accounts = listOf(
                EbSessionStore.MergedAccount(iban = "DE89370400440532013000", uid = "ex-1", currency = "EUR", name = "Existing"),
            ),
        )
        assertTrue(database.ebSessionsQueries.hasAnySession().executeAsOne())

        val accountsJson = Json.encodeToString(
            kotlinx.serialization.builtins.ListSerializer(AccountResource.serializer()),
            listOf(
                AccountResource(uid = "acc-1", iban = "AT611904300234573201", currency = "EUR", name = "Main account"),
            ),
        )
        val legacyPayload = LegacySessionPayload(
            username = "admin",
            ebSessionId = "eb-session-legacy-002",
            accountsJson = accountsJson,
            aspspName = "TestBank",
            aspspCountry = "AT",
            psuType = "personal",
        )
        val signedCookie = buildLegacyCookie(legacyPayload, signingKeyHex)

        val response = client.post("/api/login") {
            header(HttpHeaders.ContentType, ContentType.Application.Json.toString())
            header(HttpHeaders.Cookie, "bankteller-session=$signedCookie")
            setBody("""{"username":"admin","password":"changeme"}""")
        }

        assertEquals(HttpStatusCode.OK, response.status)

        // Post-condition: still only the pre-existing session — no import.
        val sessions = database.ebSessionsQueries.selectAllSessions().executeAsList()
        assertEquals(1, sessions.size)
        assertEquals("eb-session-existing", sessions[0].session_id)
    }

    @Test
    fun login_withLegacyCookie_malformedAccountsJson_loginStillSucceedsAndNothingImported() = testApplication {
        application { module() }

        val signingKeyHex = KeyStore.init(database)

        // Legacy cookie whose accountsJson is not valid JSON — the import must
        // be best-effort: login still succeeds, nothing is imported.
        val legacyPayload = LegacySessionPayload(
            username = "admin",
            ebSessionId = "eb-session-legacy-003",
            accountsJson = "{not valid json",
            aspspName = "TestBank",
            aspspCountry = "AT",
            psuType = "personal",
        )
        val signedCookie = buildLegacyCookie(legacyPayload, signingKeyHex)

        assertFalse(database.ebSessionsQueries.hasAnySession().executeAsOne())

        val response = client.post("/api/login") {
            header(HttpHeaders.ContentType, ContentType.Application.Json.toString())
            header(HttpHeaders.Cookie, "bankteller-session=$signedCookie")
            setBody("""{"username":"admin","password":"changeme"}""")
        }

        assertEquals(HttpStatusCode.OK, response.status)
        assertFalse(database.ebSessionsQueries.hasAnySession().executeAsOne())
    }
}
